name: dart_webrtc
description: Use the dart/js library to re-wrap the webrtc js interface of the browser, to adapted common browsers.
version: 1.0.7
homepage: https://github.com/flutter-webrtc/dart-webrtc
publish_to: none


environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  webrtc_interface:
    git:
      url: https://github.com/valentingrigorean/webrtc-interface

dev_dependencies:
  build_runner: ^2.2.0
  build_web_compilers: ^3.2.5
  http: ^0.13.5
  import_sorter: ^4.6.0
  pedantic: ^1.11.1
  protoo_client: ^0.3.3
  test: ^1.21.4
